#include <exception>

using namespace std;

int main()
{
	throw exception();
	return 0;
}

